# Generated by Django 3.1.2 on 2020-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(max_length=45),
        ),
    ]
